version: "3.8"

networks:
  1panel-network:
    external: true

services:
  wallos:
    container_name: ${CONTAINER_NAME}
    image: bellamy/wallos:1.26.2
    labels:
      createdBy: "Apps"
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    volumes:
      - './data/db:/var/www/html/db'
      - './data/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
    networks:
      - 1panel-network